#
# Build the ImageImport and publish 
#

name: Image Import

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_VERSION: "1.0.${{ github.run_number }}"
  CHOCOLATELY_PACKAGE: "chocolateley\\image-import.nuspec"  

jobs:

  build:
    name: Build
    runs-on: windows-latest  

    steps:
    # - name: List env
    #  run: env
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx


    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # - name: Echo Version 
    #  run: echo "Version = ${{ env.BUILD_VERSION }}"
    
    - name: Version Visual Studio SDK projects
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        version: "${{ env.BUILD_VERSION }}.0"
        assemblyVersion: "${{ env.BUILD_VERSION }}.0"
        fileVersion: "${{ env.BUILD_VERSION }}.0"
        informationalVersion: "${{ env.BUILD_VERSION }}.0"
    
    # Compile the solution
    - name: Compile solution
      run: dotnet build src\ImageImport.sln -c Release -o output
   
    # Documentation
    - name: Build Documentation
      working-directory: docfx_project
      run: docfx docfx.json
      continue-on-error: false

    - name: Remove unnecessary files
      run: del output\*.pdb,output\*.dev.json,output\*.deps.json 

    - name: Zip Binaries
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: 'binary.zip'        
        path: output
        type: 'zip'

    - name: Patch chocolately package
      run: |         
        $xml = [xml](Get-Content ${{ env.CHOCOLATELY_PACKAGE }})
        $xml.DocumentElement.metadata.version = "${{ env.BUILD_VERSION }}"
        $xml.Save("${{ env.CHOCOLATELY_PACKAGE }}")
        copy binary.zip chocolateley\tools
        Get-FileHash binary.zip

    - name: Create chocolately package
      uses: crazy-max/ghaction-chocolatey@v2
      with:
         args: pack ${{ env.CHOCOLATELY_PACKAGE }}        

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ env.BUILD_VERSION }}
          release_name: Release ${{ env.BUILD_VERSION }}

    - name: Upload binary asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binary.zip
        asset_name: Image-Import-Binary-${{ env.BUILD_VERSION }}.zip
        asset_content_type: application/zip

    - name: Upload chocolately asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Image-Import.${{ env.BUILD_VERSION }}.nupkg
        asset_name: Image-Import-Cocolately-${{ env.BUILD_VERSION }}.nupkg
        asset_content_type: application/zip

    - name: Push package to chocolately     
      if: false
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: push Image-Import.${{ env.BUILD_VERSION }}.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATELY_TOKEN }}

    # publish documentation
    - name: Publish documentation
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docfx_project/docs
        force_orphan: true
